export const SIMULATED_PROFILES = [
  { id: 'user_cold', name: 'Jean Dupont', specialty: 'Expert Froid', authorizedCategories: ['cold'] },
  { id: 'user_hot', name: 'Marie Martin', specialty: 'Chef de Cuisine', authorizedCategories: ['hot'] },
  { id: 'user_staff', name: 'Lucas Bernard', specialty: 'Serveur / Bar', authorizedCategories: ['staff'] },
  { id: 'user_light', name: 'Thomas Petit', specialty: 'Tech Lumière', authorizedCategories: ['light'] },
  { id: 'user_sound', name: 'Sophie Dubois', specialty: 'Ingé Son', authorizedCategories: ['sound'] },
  { id: 'user_video', name: 'Julie Moreau', specialty: 'Tech Vidéo', authorizedCategories: ['video'] },
  { id: 'user_pos', name: 'Marc Leroy', specialty: 'Expert Caisse', authorizedCategories: ['pos'] },
  { id: 'user_network', name: 'Alice Net', specialty: 'Tech Réseau', authorizedCategories: ['network'] },
  { id: 'user_plumbing', name: 'Pierre Legrand', specialty: 'Plombier', authorizedCategories: ['plumbing'] },
  { id: 'user_electricity', name: 'Marc Volt', specialty: 'Électricien', authorizedCategories: ['electricity'] },
  { id: 'user_coffee', name: 'Sarah Café', specialty: 'Technicien Café', authorizedCategories: ['coffee'] },
  { id: 'user_beer', name: 'Tom Brasseur', specialty: 'Installateur Tirage', authorizedCategories: ['beer'] },
  { id: 'user_security', name: 'David Roc', specialty: 'Agent Sécurité', authorizedCategories: ['security'] },
  { id: 'user_cleaning', name: 'Emma Propre', specialty: 'Agent Entretien', authorizedCategories: ['cleaning'] },
  { id: 'user_architecture', name: 'Laura Design', specialty: 'Architecte', authorizedCategories: ['architecture'] },
  { id: 'user_decoration', name: 'Claire Deco', specialty: 'Décoratrice', authorizedCategories: ['decoration'] },
  { id: 'user_painting', name: 'Paul Pinceau', specialty: 'Peintre', authorizedCategories: ['painting'] },
  { id: 'user_carpentry', name: 'Louis Bois', specialty: 'Menuisier', authorizedCategories: ['carpentry'] },
];
